apiVersion: v1
kind: Service
metadata:
  name: simpleserversvc
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30123
      protocol: TCP
  selector:
    app: java-simple-server
